user:
    hashedPassword: ENC[AES256_GCM,data:OIYBBV4fpsxY6ob1ih1Dq8K6UFl7K19V7jMNdHJbJrFksTKQh8fpmoXvCwvbGahiNnOdvy62nP/NNJYLOFj8F6a/xauE7oTAJg==,iv:6cfoG+ZGLqTxaaNFBxlhXmtazUltJZbmBEAd+uwQJ3Y=,tag:XkNNVFwyAKwug8Lte/5RQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w3e6t34j7md03gvndfv4mryvy33h8ly0l64mc3a9hk0t7jrgq52qpk7cae
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdzUrTVNMVm9lMStYenJJ
            c1ZmY3hPaXhrZnZ4T0NBK2x3T3Rxb3lIcGpvCnZUVXcreFRTSkdFbFlOUzBuc2Fm
            M1AwZEVBRm9HdW9NdHV5dW9BTkwrUHMKLS0tIEYwSGdCckpTRDMxN3NJVVhnQU1x
            cFV1WUY2dE5qZDZGalAxZ05Pcjh5LzAKpt0H/Hbb24nFFwjspDZAN96Cbt8UYCBV
            gN0ONQfh9nlNtGRw1FyDMi2v7HJJqzWr9d+VqIc2d1gNEkp3ggYbfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ltucngpwfttu5xu4aegwvqag0z68zwlme4w2ergu4337kz9yvaust0swhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU2Zqd2dFUjJUSGxlNXBU
            LzNuRys0OGhOa1dJbHlRaGxkeGJUQU1YK0RrCkY0VGV0LzQvSHYzTTV4aUZUdXp1
            djRUTnBockgrenpCZFQ0emRWdGJZZjQKLS0tIGVpa211MGdzZEM4TnJiRzBYbzV6
            T1VkaVZuMFBYMWRhdkU0UDNob3J5UlkKoIqJ079znYVEuFeIyj11PhhthSzCRi4d
            jHMpxzYzAIejo6x6upIqM4tFbnJlEAMYIKb8dNTsJUYb1puQlrsJsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-25T13:51:12Z"
    mac: ENC[AES256_GCM,data:8qbZxoqpVk4LfoIqIyfz489zwm5yAvY/Nq9OCYDvwo5ll7LIrfyuConqW6rNXkHIPqH0mFQgTxQEx6weZrb5gQjHqdiflf3usdcibpxCHc2e5l0gCiEvKMAk1/bzOOXnrj/Ogi1OHf2yIfiWsaUI9xcmCJW00Q3f2g8NI3hcF3g=,iv:8AsYjpG3PllPxT1Domzqo8MY/5uxQUH/Mm33/U+Clvs=,tag:1yILbF2Bc9Wo5MAUslnvVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
